languageCode = "en-us"
title = "Suraj Narwade"
baseURL = "https://suraj.pro"
theme = "hugo-theme-nix"
disqusShortname = "surajnarwade-github-io"


[params]
  GithubID = "surajnarwade"
  TwitterID = "red_suraj"
  LinkedInID = "suraj-narwade-85436a38"
  #GoogleplusID = "your_googleplus"
  FacebookID = "suraj.narwade.52"
  InstagramID = "red_suraj"
  Name = "Suraj Narwade"
  HeaderUsername = "suraj"
  HeaderHostname = "uSwitch"
  Email = "surajnarwade353@gmail.com"
  About = "* Platform Engineer at uSwitch * Kubernetes and Cloud Native * Contribute to OpenSource in any possible way * CNCF Ambassador * CKA * RHCA * London Dreams"
  ProfilePicture = "/headshot.jpg"
  GoogleAnalytics = "UA-153648902-1"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "talks"
    weight = 0
    url = "https://slides.suraj.pro"
  [[menu.header]]
    name = "resume"
    weight = 0
    url = "https://resume.suraj.pro"